version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: complianceai_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-asya}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Asya1234}
      POSTGRES_DB: ${DB_DATABASE:-dbcomplianceai}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: complianceai_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-123}
    ports:
      - "${PGADMIN_HOST_PORT:-5050}:80"
    depends_on:
      - db

volumes:
  postgres_data:
